import sys
import requests
import json

###############################   UPDATE THIS FILE WITH NEW CLAN MEMBERS   ################################
clan_list1 = {
    'brocaleb': '908P88J0', 
    '!!Aristocrat!!': '2VY0YVR08', 
    'YokoEno': '8JPU0228P', 
    'Little Roodie!': 'PQP8VQ8Q', 
    'Roodies Raiders': 'YUQ0UQJV', 
    'Neo': 'VQQ0LGPQ', 
    'Luke': 'P9QQYCVC', 
    '■LORD RAJ■': '2V8PVJG', 
    'Megs Over Easy': '9PP9JL82', 
    'ItsTwinkie': 'YGJYYCJ2', 
    'alalalalalala': 'PP9QLQYY', 
    'kat': '98JQG9R98', 
    'CRASH': '2UQ2UGY8G', 
    'rackam': '28PVPV2LU', 
    'Ryan': '29JPVQ8Q', 
    'Luffy': '28PQGLVYL', 
    'jay': 'QCR0UYJ2', 
    'hay': '99CJPCY9L', 
    'Juliet': 'GJQCY2U', 
    'Zookstar123': 'L892JRQ89', 
    'MonseurMaiDra': '880YP8LQC', 
    'Chris': 'QC2G880UG', 
    'Trumpy': 'Q9QQCVLV', 
    'PlausibleAnt': '9VCU9RJPC', 
    'The Aristocrat': 'PCLY8GLL', 
    'KornHub': 'R8VQU9YL', 
    '69 For Dayz': 'YQ2U0P8Q', 
    'weel': '8R08JVRP', 
    'Big Aristocrat': 'RP2YJVPP', 
    'LoonGoon': 'GPRL28R9', 
    'patrick': 'LLRYQPP89', 
    'Inception': 'PCP2G9U8', 
    'Super Bee': 'UVGQPYVV', 
    'RONNIE': '90RQY0YCY', 
    'adanac10': '28GVR820U', 
    '♡♡DEBADRITA♡♡': '8829LRQP', 
    'babyrackam': 'LJL89Y8G8', 
    "PlausibleShan't": 'QPQ9228LQ', 
    'eeBrepuS': '28GJJYU0J', 
    'Joe': 'J9VQ28QQ', 
    'BABY dom': '9GURLYGC', 
    'Joseph': 'U2R9PR9V', 
    'biglopp': '8CPVGU0V', 
    'Legend Hash': '2829UUQGV', 
    'anubhab': 'VRCGVLPC', 
    'Max The Monkey': 'G9JR0JGG', 
    'spencer': '82Y8L009', 
    'void': '2C2PRLJYQ', 
    'Ry Ry': '20YUYLLL', 
    'Dark Valley': '9RCPY8J9R',
}